config/routes.rb
Musicbox::Application.routes.draw do

  get "comment/new"

  get "comment/create"

  get "comment/show"

  get "comment/index"

  
  match "/comment",:to => "tracks#create_comment"
  
  match "/download",:to =>"tracks#download"
  resources :tracks

  devise_for :artists do 
  	match '/artist', :controller =>'artists',:action =>'show',:as => :artist_root
  end
  devise_for :artists, :controllers =>{:registrations => "registrations"}

  namespace :artist do 
	  root :to => "artists#register"
  end

 resources :artists, :only =>[:index,:show, :edit, :destroy, :update]
 match '/featured', :to => 'artists#index'
 match '/about', :to => 'home#about'
 match '/contact', :to =>'home#contact'

 resource :microposts
 
 match '/personal_tracks', :to =>'tracks#personal_tracks'

  get "pages/home"

  get "pages/about"

 

  

   root :to => "home#index"

end

app/models/track.rb
class Track < ActiveRecord::Base
	acts_as_commentable
	
	belongs_to :artist
    attr_accessible :name,:uploaded_data

	has_attachment :content_type =>'audio/mp3', # will accept mp3 mixtapes for now
		       :storage =>:file_system,
		       :max_size => 700.megabytes,
		       :path_prefix =>'public/tracks',
		       :partition => false

	validates_as_attachment


end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  # GET /tracks
  # GET /tracks.xml
  def index
    @tracks = Track.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tracks }
    end
  end

  # GET /tracks/1
  # GET /tracks/1.xml
  def show
    @track = Track.find(params[:id])

    @artists = Artist.all

   	@comments = @track.comments.paginate(:page =>params[:page])
    
    

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @track }
    end
  end

  # GET /tracks/new
  # GET /tracks/new.xml
  def new
    @track = Track.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @track }
    end
  end

  # GET /tracks/1/edit
  def edit
    @track = Track.find(params[:id])
  end

  # POST /tracks
  # POST /tracks.xml
  def create
    @artist = current_artist
    @track = @artist.tracks.build(params[:track])
  #  @track = Track.new(params[:track])

    respond_to do |format|
      if @track.save
        format.html { redirect_to(@track, :notice => 'Track was successfully created.') }
        format.xml  { render :xml => @track, :status => :created, :location => @track }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @track.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tracks/1
  # PUT /tracks/1.xml
  def update
    @track = Track.find(params[:id])

    respond_to do |format|
      if @track.update_attributes(params[:track])
        format.html { redirect_to(@track, :notice => 'Track was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @track.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.xml
  def destroy
    @track = Track.find(params[:id])
    @track.destroy

    respond_to do |format|
      format.html { redirect_to(tracks_url) }
      format.xml  { head :ok }
    end
  end

  
  
 def personal_tracks 
 	@artist = Artist.find(params[:id])
 end
 	
 def create_comment
 		@track = Track.find(params[:id])
 		
 		
  if @track.comments.create(:comment =>params[:comment],:artist_id =>current_artist.id)
       
  	   @comments = @track.comments.paginate(:page =>params[:page])
 	   render 'show'	
 		else
 			#must do something when cant create comment
 end
 		
 		end
 		
 		
 def download
 	
  send_file "#{RAILS_ROOT}/public/tracks/#{params[:track]}",:type =>'audio/mp3',:filename =>"www.mculobox.com.mp3"
  #note must do something after sending the file:
   #it does send the file but stops the song...
 
end
 	
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<%= form_for(@track,:html =>{:multipart => true}) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class ="fields">
  	
   
  	
   <%=f.label :Track %><br/>
   <%=f.file_field :uploaded_data %><br/>
  
   
   <%=f.label :Title%>
   <%=f.text_field :name%>
   </div>
  <div class="actions">
    <%= f.submit "Upload Track" %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<h1>Listing tracks</h1>


	<div class ="listing">
		<%if @tracks.empty?%>
		 There are currently no tracks on the system
		<%end%>
<% @tracks.each do |track| %>
		<div class ="element-preview">
		<%= link_to (image_tag(picture(track.artist),:size =>'96x96'), track )%>
		 <div class ="meta">
		 	<%=link_to (track.name, track ) %> by <%=link_to (track.artist.username)%><br/>
		 	Uploaded:<%=time_ago_in_words(track.created_at)%>
		 	</div>
		
		</div >
		

	
<% end %>
	</div>

app/views/tracks/new.html.erb
<h1>New track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/personal_tracks.html.erb
<%if artist_signed_in?%> 

      <%if current_artist.tracks.empty? then  %>
         There are currently no Tracks

 <%else%>
	 <table>
		 <tr>
			 <td></td>
			 <td></td>
			 <td></td>
		 </tr> 
 

 	<% current_artist.tracks.each do |track| %>
		<tr>	
			<td>  <%=link_to track.name,track%></td>
			<td>	<%=link_to 'Edit',edit_track_path(track)%></td>
			<td>	<%=link_to 'Delete',track,:confirm =>'Are you sure?',:method =>:delete %></td>
      </tr>
  <%end%>
</table>
 
  
  <%end%>
<%else%>
<%if @artist.tracks.empty?%>
	There are currently no Tracks..
	<%else%>
	 <table>
		 <tr>
			 <td></td>
			 <td></td>
			 <td></td>
		 </tr> 
 

 	<% @artist.tracks.each do |track| %>
		<tr>	
			<td>  <%=link_to track.name,track%></td>
			
      </tr>
  <%end%>
</table>
<%end%>
<%end%>
  <%if artist_signed_in?%>
   <%=link_to("New Track",new_track_path)%> 
  <%end%>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>


<audio src =<%= "/tracks/#{@track.filename}"%>  autoplay ="autoplay" controls ="controls">
	
Your broswer does not have HTML 5 support
</audio>


<p><strong><%=@track.name%></strong> Posted by<%= link_to(@track.artist.username,@track.artist) %><br/>
	<%=link_to "Download",:controller =>"tracks",:action =>"download",:track => @track.filename%>
</p>


<%if artist_signed_in?%>
    <%=form_tag({:controller => :tracks,:action =>:create_comment,:id=>@track.id},{:method => :post} ) do |f|%>
   <%=text_area_tag :comment%>
   <%=submit_tag "Comment"%>
<%end%>
<%end%>
   

<p>Comments: </p>
    <% unless  @comments.empty?%>
     <%@comments.each do |c|%>
     
 <div id ="comments"> 
 
    <div class ="thumbs"> 
         <%=link_to (image_tag(picture(c.artist),:size =>"50x50")),:controller => "artists",:action => "show",:id => c.artist_id%>
    </div>
     <div id ="comment-text"> 
    <strong><%=c.artist.username%></strong>(<%=time_ago_in_words(c.created_at)%> ago) :<br/>
                  
                	<%=c.comment%>
             
                </div>
 </div> 
	 
	 
	 
        <%end%>
          <%=will_paginate @comments ,:id =>@track.id%>

    <%end%>