musicbox/config/routes.rb
Musicbox::Application.routes.draw do

 resources :tracks
 
 devise_for :artists
 devise_for :artists, :controller =>{:registrations => "registrations", :sessions => "sessions"}

 namespace :artist do
 	root :to => "artists#show"
 end
 	
 resources :artists, :only => [:index, :show, :edit, :distroy, :update]
 match '/featured' ,:to => 'artists#index'
 match '/member' ,:to => 'artists#member'
 match '/about', :to=> 'home#about'
 match '/contact',:to=> 'home#contact'
 
 resources :microposts

   root :to => "home#index"

end

musicbox/app/models/artist.rb
class Artist < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me, :genre, :record_label, :artist_type, :website, :login,:bio,:location,:dob,:gender,:languages
  attr_accessor :rating, :login
	
  has_one :photo, :dependent => :destroy
  has_many :microposts, :dependent => :destroy
  has_many :tracks

  protected
  def self.find_for_database_authentication(warden_conditions)
	conditions = warden_conditions.dup
	login = conditions.delete(:login)
	where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  end

  def self.send_reset_password_instructions(attributes={})
	recoverable = find_recoverable_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
	recoverable.send_reset_password_instructions if recoverable.persisted?
	recoverable
  end

  def self.find_recoverable_or_initialize_with_errors(required_attributes, attributes, error=:invalid)
	(case_insensitive_keys||[]).each{|k| attributes[k].try(:downcase!)}

	attributes = attributes.slice(*required_attributes)
	attributes.delete_if{ |key,value| value.blank? }

	if attributes.size == required_attributes.size
		if attributes.has_key?(:login)
			login = attributes.delete(:login)
			record = find_record(login)
		else
			record = where(attributes).first
		end
	end

	unless record
		record = new

		required_attributes.each do |key|
			value = attributes[key]
			record.send("#{key}=", value)
			record.errors.add(key, value.present? ? error : :blank)
		end
	end
	record
  end
  
  def self.find_record(login)
	  where(["username = :value OR email = value", { :value => login }]).first
  end
end

musicbox/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_filter :authenticate_artist!
  #Prepare data to show all artist on our database:
  def index
	  @title = "Featured Artists"
      #	  @artists =Artist.all   ,had to change this since using will_paginate
	  @artists = Artist.paginate(:page=>params[:page])
  end

 def show
 	@artist = current_artist
 	 current_member = Artist.find(params[:id])
	 if (current_member.id == 0)
 		@artist = current_artist
 	 else
 	 	@artist = current_member
 	 end
 end
 
  def edit
	  @artist = Artist.find(params[:id])
	  @title = "Edit User"
  end

  def update
	  @artist = Artist.find(params[:id])

	  unless params[:attachable].blank?
	  @photo = @artist.build_photo(params[:attachable])
          @photo.save
	  #what if there was a problem saving the image
          end

	  
	  if @artist.update_attributes(params[:artist])
		  flash[:success] ='Succesfully updated your profile'
		  redirect_to @artist
	  else
		  @title = "Edit User"
		  render 'edit'
	  end
  end

  def delete
  end
 

end

musicbox/app/helpers/artists_helper.rb
module ArtistsHelper

end

musicbox/app/views/artists/_artist.html.erb
<li>
<div class= "clipwrapper">
	<div class="clip">
		<%=link_to image_tag(picture(artist), :size => '180x180'),artist_path(artist.id)%>
	</div>
           
	<div class= "public_info">
	  |<%=artist.username %>
	 </div>
</div>
</li>

musicbox/app/views/artists/edit.html.erb
<h1> Edit Profile</h1>



<%=form_for(@artist,:html =>{:multipart => true}) do |f| %> 

	<p>
	<%=f.label :Name %> <br/>
	<%=f.text_field :username %>

	<p>
	<%=f.label "About You" %><br/>
	 <%=f.text_area :bio %>
	</p>
	<p>
	<%=f.label :location %><br/>
	<%=f.text_field :location %>
       </p>

	<p>
	<%=f.label "Artist type " %><br/>
	<%=f.select(:artist_type,[['Commercial',1],['Independent',2],['Unsigned',3]])%>
	</p>


	<p>
	</p>
	<%=f.label :website %><br/>
	<%=f.text_field :website %>
	</p>

	<p>
	<%=f.label :Genre %><br/>
	<%=f.text_field :genre %>
	</p>

	
	<p>
	<%=f.label "Record Label" %><br/>
	<%=f.text_field :record_label%>
	</p>

      <p>
	<%= label_tag :Picture %><br/>
	<%= file_field :attachable, :uploaded_data %>
      </p> 

        <p>	 
        <%=f.submit "Save" %>
	</p>

        

<%end%>

musicbox/app/views/artists/index.html.erb
<h1>Featured Artists</h1>
<%=will_paginate %>
<ul >
	
	<%@artists.each do |artist| %>
		<%=render artist %>
	<%end%>
</ul>
<%=will_paginate %>

musicbox/app/views/artists/register.html.erb
<p>
Confirm your email address,.....
</p>

musicbox/app/views/artists/show.html.erb
<div id ="profile" >
<div class ="profile-picture">
	<%=image_tag(picture(@artist),:size =>'180x180')%>
	
</div>
<div id ="info">
	<h2><%=@artist.username %></h2>
	<p>
	<%if artist_signed_in?%>
		About You:<%=@artist.bio %><br/>
	<%else%>
		About <%=@artist.username %>:<br/>
		<%=@artist.bio %>
	<%end%>
	
	Location:<%=@artist.location %><br/>
        Genre :	<%=@artist.genre%><br/>
	Record Label: <%=@artist.record_label %><br/>
	HomePage:<%=@artist.website %><br/>
	</p>	
</div>

<div id="user_resources">
	<ul>
		<% if artist_signed_in? %>
			<%=link_to 'Edit Profile',edit_artist_path(@artist) %>
	
		<%end%>
		<li><%=link_to 'Tracks' ,tracks_path%></li>
		<li><%=link_to 'Mixtapes','#'%></li>
		<li><%=link_to'Albums','#'%></li>
		<li><%=link_to 'Events','#'%></li>
		<li><%=link_to 'Blog','#'%></li>
	</ul>
</div>

</div>

musicbox/app/views/artists/update.html.erb
<h1>Artists#update</h1>
<p>Find me in app/views/artists/update.html.erb</p>